import { readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * Interface text carries no em dash (#179, spec #167 poles-teks). The em dash was the tell of copy
 * that read as translated rather than written, so the rule is enforced here instead of by review:
 * every value in both message catalogs, and the markup of every `.svelte` file under `src/`, must be
 * free of U+2014.
 *
 * Code comments are not interface text, so HTML comments and whole `<script>` and `<style>` blocks
 * are blanked out before a component is searched. A `<script>` can still build visible text, and
 * such a string is still covered by the rule; the test cannot tell it from a comment, so review
 * keeps that half.
 *
 * The character is built from its code point so that this file does not itself contain it.
 */

const EM_DASH = String.fromCodePoint(0x2014);
const ROOT = fileURLToPath(new URL('../..', import.meta.url));
const CATALOGS = ['messages/id.json', 'messages/en.json'];
/** Generated by paraglide from the catalogs, git-ignored, and already covered through them. */
const SKIPPED_DIRECTORIES = new Set([join(ROOT, 'src', 'lib', 'paraglide')]);

/**
 * The parts of a component that are code rather than interface text. A `<style>` block counts: its
 * only prose is CSS comments, which the ticket leaves alone as it leaves every code comment.
 */
const HIDDEN_DELIMITERS = [
	{ open: '<!--', close: '-->' },
	{ open: '<script', close: '</script>' },
	{ open: '<style', close: '</style>' }
];

function svelteFilesUnder(directory: string): string[] {
	const found: string[] = [];
	for (const entry of readdirSync(directory, { withFileTypes: true })) {
		const path = join(directory, entry.name);
		if (entry.isDirectory()) {
			if (!SKIPPED_DIRECTORIES.has(path)) {
				found.push(...svelteFilesUnder(path));
			}
		} else if (entry.name.endsWith('.svelte')) {
			found.push(path);
		}
	}
	return found;
}

/** Every character of `text` replaced by a space except line breaks, so line numbers survive. */
function blank(text: string): string {
	return text.replaceAll(/[^\n]/g, ' ');
}

/** The first hidden range that starts at or after `from`, as start and end offsets. */
function nextHiddenRange(source: string, from: number): { start: number; end: number } | undefined {
	let next: { start: number; end: number } | undefined;
	for (const { open, close } of HIDDEN_DELIMITERS) {
		const start = source.indexOf(open, from);
		if (start !== -1 && (next === undefined || start < next.start)) {
			const closeAt = source.indexOf(close, start + open.length);
			next = { start, end: closeAt === -1 ? source.length : closeAt + close.length };
		}
	}
	return next;
}

/** The component source with every HTML comment, `<script>` and `<style>` block blanked out. */
function visibleMarkup(source: string): string {
	let visible = '';
	let index = 0;
	let range = nextHiddenRange(source, index);
	while (range) {
		visible += source.slice(index, range.start) + blank(source.slice(range.start, range.end));
		index = range.end;
		range = nextHiddenRange(source, index);
	}
	return visible + source.slice(index);
}

describe('visibleMarkup', () => {
	it('blanks comments, script and style blocks and keeps line numbers', () => {
		const source = [
			'<script lang="ts">',
			`\t// a ${EM_DASH} comment`,
			'</script>',
			`<!-- note ${EM_DASH} here -->`,
			`<p>kept ${EM_DASH}</p>`,
			`<style>/* css ${EM_DASH} comment */</style>`
		].join('\n');
		const lines = visibleMarkup(source).split('\n');

		expect(lines).toHaveLength(6);
		expect(lines.filter((line) => line.includes(EM_DASH))).toEqual([`<p>kept ${EM_DASH}</p>`]);
	});
});

describe('no em dash in interface text', () => {
	it.each(CATALOGS)('%s has no value containing an em dash', (catalog) => {
		const messages: Record<string, unknown> = JSON.parse(readFileSync(join(ROOT, catalog), 'utf8'));
		const offenders = Object.entries(messages)
			.filter(([, value]) => JSON.stringify(value).includes(EM_DASH))
			.map(([key]) => key);

		expect(offenders).toEqual([]);
	});

	it('no .svelte file under src/ has an em dash outside a comment, <script> or <style>', () => {
		const files = svelteFilesUnder(join(ROOT, 'src'));
		const offenders: string[] = [];
		for (const file of files) {
			const lines = visibleMarkup(readFileSync(file, 'utf8')).split('\n');
			lines.forEach((line, index) => {
				if (line.includes(EM_DASH)) {
					offenders.push(`${relative(ROOT, file)}:${index + 1}`);
				}
			});
		}

		expect(files.length).toBeGreaterThan(0);
		expect(offenders).toEqual([]);
	});
});
