import { readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import { describe, expect, it } from 'vitest';

/**
 * Interface text carries no em dash (#179, spec #167 poles-teks). The em dash was the tell of copy
 * that read as translated rather than written, so the rule is enforced here instead of by review:
 * every value in both message catalogs, the markup of every `.svelte` file under `src/`, and every
 * string or template literal in `src/lib/server/email/templates/*.ts` (#198), must be free of
 * U+2014.
 *
 * Code comments are not interface text, so HTML comments and whole `<script>` and `<style>` blocks
 * are blanked out before a component is searched. A `<script>` can still build visible text, and
 * such a string is still covered by the rule; the test cannot tell it from a comment, so review
 * keeps that half. The email templates are `.ts` rather than `.svelte`, so their comments and
 * strings are told apart with the TypeScript scanner instead (see `stringEmDashLines` below):
 * `skipTrivia` drops a comment before it ever becomes a token, so a `//` inside a string such as
 * `'https://...'` is never mistaken for one.
 *
 * The character is built from its code point so that this file does not itself contain it.
 */

const EM_DASH = String.fromCodePoint(0x2014);
const ROOT = fileURLToPath(new URL('../..', import.meta.url));
const CATALOGS = ['messages/id.json', 'messages/en.json'];
const EMAIL_TEMPLATES_DIR = join(ROOT, 'src', 'lib', 'server', 'email', 'templates');
/** Generated by paraglide from the catalogs, git-ignored, and already covered through them. */
const SKIPPED_DIRECTORIES = new Set([join(ROOT, 'src', 'lib', 'paraglide')]);

/**
 * The parts of a component that are code rather than interface text. A `<style>` block counts: its
 * only prose is CSS comments, which the ticket leaves alone as it leaves every code comment.
 */
const HIDDEN_DELIMITERS = [
	{ open: '<!--', close: '-->' },
	{ open: '<script', close: '</script>' },
	{ open: '<style', close: '</style>' }
];

function svelteFilesUnder(directory: string): string[] {
	const found: string[] = [];
	for (const entry of readdirSync(directory, { withFileTypes: true })) {
		const path = join(directory, entry.name);
		if (entry.isDirectory()) {
			if (!SKIPPED_DIRECTORIES.has(path)) {
				found.push(...svelteFilesUnder(path));
			}
		} else if (entry.name.endsWith('.svelte')) {
			found.push(path);
		}
	}
	return found;
}

/** Every character of `text` replaced by a space except line breaks, so line numbers survive. */
function blank(text: string): string {
	return text.replaceAll(/[^\n]/g, ' ');
}

/** The first hidden range that starts at or after `from`, as start and end offsets. */
function nextHiddenRange(source: string, from: number): { start: number; end: number } | undefined {
	let next: { start: number; end: number } | undefined;
	for (const { open, close } of HIDDEN_DELIMITERS) {
		const start = source.indexOf(open, from);
		if (start !== -1 && (next === undefined || start < next.start)) {
			const closeAt = source.indexOf(close, start + open.length);
			next = { start, end: closeAt === -1 ? source.length : closeAt + close.length };
		}
	}
	return next;
}

/** The component source with every HTML comment, `<script>` and `<style>` block blanked out. */
function visibleMarkup(source: string): string {
	let visible = '';
	let index = 0;
	let range = nextHiddenRange(source, index);
	while (range) {
		visible += source.slice(index, range.start) + blank(source.slice(range.start, range.end));
		index = range.end;
		range = nextHiddenRange(source, index);
	}
	return visible + source.slice(index);
}

describe('visibleMarkup', () => {
	it('blanks comments, script and style blocks and keeps line numbers', () => {
		const source = [
			'<script lang="ts">',
			`\t// a ${EM_DASH} comment`,
			'</script>',
			`<!-- note ${EM_DASH} here -->`,
			`<p>kept ${EM_DASH}</p>`,
			`<style>/* css ${EM_DASH} comment */</style>`
		].join('\n');
		const lines = visibleMarkup(source).split('\n');

		expect(lines).toHaveLength(6);
		expect(lines.filter((line) => line.includes(EM_DASH))).toEqual([`<p>kept ${EM_DASH}</p>`]);
	});
});

describe('no em dash in interface text', () => {
	it.each(CATALOGS)('%s has no value containing an em dash', (catalog) => {
		const messages: Record<string, unknown> = JSON.parse(readFileSync(join(ROOT, catalog), 'utf8'));
		const offenders = Object.entries(messages)
			.filter(([, value]) => JSON.stringify(value).includes(EM_DASH))
			.map(([key]) => key);

		expect(offenders).toEqual([]);
	});

	it('no .svelte file under src/ has an em dash outside a comment, <script> or <style>', () => {
		const files = svelteFilesUnder(join(ROOT, 'src'));
		const offenders: string[] = [];
		for (const file of files) {
			const lines = visibleMarkup(readFileSync(file, 'utf8')).split('\n');
			lines.forEach((line, index) => {
				if (line.includes(EM_DASH)) {
					offenders.push(`${relative(ROOT, file)}:${index + 1}`);
				}
			});
		}

		expect(files.length).toBeGreaterThan(0);
		expect(offenders).toEqual([]);
	});
});

/** The token kinds that hold literal text: a plain string, and every piece of a template literal. */
function isStringLikeToken(kind: ts.SyntaxKind): boolean {
	return (
		kind === ts.SyntaxKind.StringLiteral ||
		kind === ts.SyntaxKind.NoSubstitutionTemplateLiteral ||
		kind === ts.SyntaxKind.TemplateHead ||
		kind === ts.SyntaxKind.TemplateMiddle ||
		kind === ts.SyntaxKind.TemplateTail
	);
}

/** 1-based line number of `pos` in `source`. */
function lineOfPos(source: string, pos: number): number {
	return source.slice(0, pos).split('\n').length;
}

/**
 * One `}` encountered while at least one `${ }` substitution is open. If it closes the
 * substitution, the scanner is told, with `reScanTemplateToken`, to keep reading the template
 * literal instead of an expression. Otherwise it closes an ordinary brace nested inside that
 * expression (an object literal, a block), and scanning just continues.
 */
function closeTemplateBrace(scanner: ts.Scanner, substitutionDepths: number[]): ts.SyntaxKind {
	const top = substitutionDepths.length - 1;
	if (substitutionDepths[top] === 0) {
		substitutionDepths.pop();
		return scanner.reScanTemplateToken(false);
	}
	substitutionDepths[top] -= 1;
	return scanner.scan();
}

/**
 * The line numbers of `source` where a string literal, or a piece of a template literal, contains an
 * em dash. Built from `ts.createScanner` rather than a regex: with `skipTrivia` on, a comment never
 * reaches the token stream at all, so it cannot be mistaken for a string, and a `//` inside a string
 * such as `'https://...'` is never mistaken for the start of one.
 *
 * `substitutionDepths` holds one entry per currently open `${ }`, counting the braces nested inside
 * its own expression, so a `}` that merely closes an object literal inside a substitution is not
 * confused with the `}` that ends the substitution itself.
 */
function stringEmDashLines(source: string): number[] {
	const scanner = ts.createScanner(
		ts.ScriptTarget.Latest,
		true,
		ts.LanguageVariant.Standard,
		source
	);
	const lines: number[] = [];
	const substitutionDepths: number[] = [];

	let kind = scanner.scan();
	while (kind !== ts.SyntaxKind.EndOfFileToken) {
		if (isStringLikeToken(kind)) {
			if (scanner.getTokenText().includes(EM_DASH)) {
				lines.push(lineOfPos(source, scanner.getTokenPos()));
			}
			if (kind === ts.SyntaxKind.TemplateHead || kind === ts.SyntaxKind.TemplateMiddle) {
				substitutionDepths.push(0);
			}
			kind = scanner.scan();
			continue;
		}
		if (kind === ts.SyntaxKind.OpenBraceToken && substitutionDepths.length > 0) {
			substitutionDepths[substitutionDepths.length - 1] += 1;
			kind = scanner.scan();
			continue;
		}
		if (kind === ts.SyntaxKind.CloseBraceToken && substitutionDepths.length > 0) {
			kind = closeTemplateBrace(scanner, substitutionDepths);
			continue;
		}
		kind = scanner.scan();
	}
	return lines;
}

describe('stringEmDashLines', () => {
	it('rejects an em dash inside a plain string literal', () => {
		const source = `const a = 'kata sandi ${EM_DASH} rahasia';`;

		expect(stringEmDashLines(source)).toEqual([1]);
	});

	it('accepts an em dash inside a comment', () => {
		const source = `// catatan ${EM_DASH} boleh\nconst a = 'aman';`;

		expect(stringEmDashLines(source)).toEqual([]);
	});

	it('rejects an em dash after "https://" inside a string, not mistaken for a comment', () => {
		const source = `const a = 'https://contoh ${EM_DASH} teks';`;

		expect(stringEmDashLines(source)).toEqual([1]);
	});

	it('rejects an em dash in the tail of a template literal that has a substitution', () => {
		const source = 'const greeting = `Halo ${who} ' + EM_DASH + ' selamat`;';

		expect(stringEmDashLines(source)).toEqual([1]);
	});

	it('does not mistake a brace nested inside a substitution for the one that closes it', () => {
		const source = 'const greeting = `Halo ${format({ n: 1 })} ' + EM_DASH + ' selamat`;';

		expect(stringEmDashLines(source)).toEqual([1]);
	});
});

describe('no em dash in email template strings', () => {
	const files = readdirSync(EMAIL_TEMPLATES_DIR, { withFileTypes: true })
		.filter((entry) => entry.isFile() && entry.name.endsWith('.ts'))
		.map((entry) => join(EMAIL_TEMPLATES_DIR, entry.name));

	it('found the email templates to check', () => {
		expect(files.length).toBeGreaterThan(0);
	});

	it.each(files.map((file) => ({ file, name: relative(ROOT, file) })))(
		'$name has no em dash in a string or template literal',
		({ file }) => {
			expect(stringEmDashLines(readFileSync(file, 'utf8'))).toEqual([]);
		}
	);
});
